// Generated by CoffeeScript 1.12.7
var CWebp, DWebp, exports, fs, pkg, ref, version;

fs = require('fs');

ref = require('./webp'), CWebp = ref.CWebp, DWebp = ref.DWebp;

module.exports = exports = CWebp;

exports.CWebp = CWebp;

exports.DWebp = DWebp;

exports.version = version;
