name: Build + Tets (Jest/Cypress) + Publish

on: [push]

jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v1
        
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run compile --if-present
    - run: npm run test:all

  publish:
    runs-on: macos-latest
    steps:
    - run: npm publish
    - name: Publish to npm if version has been updated
      uses: pascalgn/npm-publish-action@1.1.0
      with:
        tag_name: "v%s"
        tag_message: "v%s"
        commit_pattern: "^Release (\\S+)"
    env:
      NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      CI: true
